CREATE TABLE users
(
    user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name       VARCHAR(255)                            NOT NULL,
    user_email      VARCHAR(255)                            NOT NULL,
    user_type       VARCHAR(255)                            NOT NULL,
    currency_amount DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);